ITDA-project/client

src/navigations/Auth.js
src/screens/DeleteAccount.js

✨[feature]  회원탈퇴 화면 구현

---

src/components/Input.js
src/navigations/Auth.js
src/screens/ApplicationForm.js

✨feat : 신청서 작성 화면 구현

---

.idea/.gitignore
.idea/vcs.xml
src/navigations/Main.js
src/navigations/index.js
src/screens/AllPosts.js
src/screens/EditProfile.js
src/screens/MainPage.js
src/screens/MyPage.js
src/screens/Profile.js
src/screens/PublicProfile.js

✨[feature]헤더스타일수정

---

ios/Podfile.lock
src/screens/Signin.js

✨[feature] android 환경에서 네이버 로직 구현

---

src/screens/ApplicationDecision.js
src/screens/ApplicationList.js

✨[feature] 신청서 확인 화면 구현

---

src/contexts/AuthContext.js
src/screens/Profile.js
src/screens/Signin.js
src/screens/SigninWithEmail.js

✨[feature] 로그아웃 연결

---

src/screens/AllPosts.js
src/screens/MainPage.js

<br>
메인페이지, 전체글 페이지 백 연결 코드 추가

✨[feature] 메인,전체글 백연결

---

src/screens/Signin.js
src/screens/Signup.js

🐞[bugfix] 중복 이메일 경고 띄우기

---

src/screens/MyPostDetail.js
src/screens/PostDetail.js

<br>
게시글 상세보기 백연결 코드 (좋아요 수정 필요)

✨[Feature]게시글 상세보기 백연결

---

src/screens/CreatePost.js

✨[feature] 게시글 생성 백연결

---

src/hooks/useRequireLogin.js
src/navigations/Main.js
src/screens/CreatePost.js
src/screens/MainPage.js
src/screens/MyPage.js

#65 
<br>
마이페이지 백연결 + 연결시 발생한 오류들 수정

✨[Feature]마이페이지 백연결 

---

src/screens/Search.js

✨[Feature] 검색 화면 백연결

---

src/navigations/Home.js
src/navigations/Main.js
src/screens/Chat.js
src/screens/ChatList.js
src/screens/CreatePost.js
src/screens/EditPost.js
src/screens/MyPostDetail.js
src/screens/PostDetail.js
src/screens/index.js

✨[Feature] 채팅 화면 구현

---

src/screens/AllPosts.js
src/screens/MainPage.js
src/screens/MyPage.js

<br>
response에서 currentUserid 추출 수정 (res.data -> res.data.data)
currentUser -> currentUserId 변수명 수정

🐞[Bugfix] currentUserid 추출 수정, 변수명 수정

---

src/screens/AllPosts.js
src/screens/Notifications.js

#78 
<br>
- ✨feat: 알림화면 구현
- ♻️refactor: AllPost 화면 포커스시 재로딩 되도록
(useEffect->useFocusEffect)

✨[Feature] 알림 화면 구현

---

src/screens/ApplicationForm.js
src/screens/PostDetail.js

✨[feature] 신청서 작성 백 연결

---

src/screens/MyPostDetail.js
src/screens/PostDetail.js

<br>
모집시작 기간 날짜 형식 변경 YYYY.MM.DD -> YYYY-MM-DD

🎨[Style] 모집시작 기간 날짜 형식 변경

---

src/contexts/AuthContext.js
src/screens/ApplicationDecision.js
src/screens/ApplicationList.js
src/screens/DeleteAccount.js
src/screens/MyPostDetail.js
src/screens/PostDetail.js

#83 
<br>
신청서 목록 연결
신청서 거절, 승인 상태 변경

✨[feature] 신청서 목록 연결

---

android/app/src/main/AndroidManifest.xml
app.json
src/screens/EditProfile.js
src/screens/Notifications.js

<br>
feat: 결제 요청시 모달 화면 구현
bugfix: 프로필 사진 수정 오류 해결

✨[Feature] 결제요청시 모달 화면 구현 / 🐞[BugFix] 프로필 사진 수정 오류

---

src/screens/Chat.js
src/screens/Notifications.js

✨[Feature] 모임 참여상태 여부 배지 추가 

---

.gitignore
package-lock.json
package.json
src/screens/Chat.js

✨{Feature]안드로이드 알림 FCM 설정

---

src/screens/EditPost.js
src/screens/MyPostDetail.js
src/screens/PostDetail.js

#96 
<br>
모집기간 마감시 상세게시글 상태 변경

✨[Feature] 모집기간 마감시 상세게시글 상태 변경

---

android/app/src/main/AndroidManifest.xml
package-lock.json
package.json
src/screens/Notifications.js
src/screens/PaymentScreen.js

✨[feature] 결제 백 연결

---

src/screens/Chat.js
src/screens/ChatList.js
src/screens/CheckParticipants.js

#91 
<br>
채팅방 나가기 버튼 추가
주최자가 채팅방 나가면 채팅방 비활성화(입력 x)
주최자에게만 모임시작, 모임종료 버튼 활성화

✨[feature] 채팅방 내 참가자, 주최자 여부에 따른 UI 분기

---

src/screens/Chat.js
src/screens/ReviewForm.js

✨[feature] 리뷰 화면 구현, 백 연결

---

src/screens/Chat.js
src/screens/Notifications.js
src/screens/Profile.js

<br>
🐞bugfix: 채팅방 내 모임종료 후 뒤로가기 버튼 비활성화 문제 수정
✨feat: 알림목록 내 결제완료 알림 누르면 Alert 추가
🎨style: 프로필 내 경력수정 버튼 크기 수정( >width:100%) & Container 패딩 수정

🐞bugfix: 채팅방내 모임종료 후 뒤로가기 버튼 비활성화 문제 수정 외 2개

---

src/components/AlertModal.js
src/screens/ApplicationDecision.js
src/screens/ApplicationForm.js
src/screens/ApplicationList.js
src/screens/CreatePost.js
src/screens/DeleteAccount.js
src/screens/EditPost.js
src/screens/EditProfile.js
src/screens/FindPw.js
src/screens/MyPostDetail.js
src/screens/PaymentScreen.js
src/screens/PostDetail.js
src/screens/ReviewForm.js
src/screens/Search.js

<br>
alert -> alertmodal
좀 더 보기 좋게 수정함

🎨[style] alert -> alertmodal

---

package-lock.json
package.json
src/components/ChatModal.js
src/screens/Chat.js
src/screens/CheckParticipants.js

🎨[style] 참여/불참 표시 오른쪽 정렬

---

src/screens/CreatePost.js

게시글 생성 후 뒤로가기 시 생성 페이지로 돌아가는 문제 해결
<br>
게시글 생성 후 뒤로가기 시 생성 페이지로 돌아가는 문제 해결

🐞[bugfix] 게시글 생성 후 뒤로가기 시 생성 페이지로 돌아가는 문제 해결

---

src/screens/Chat.js

🐞[bugfix] 채팅시 프로필사진 안 보이는 문제 해결

---

src/screens/ApplicationForm.js
src/screens/Chat.js
src/screens/PostDetail.js

🐞[Bugfix] 신청서 제출시: 신청하기 버튼 -> 신청완료& 비활성화

---

src/navigations/Home.js
src/screens/Chat.js
src/screens/ChatList.js
src/screens/Notifications.js

✨[Feature] 채팅+알림 안 읽은 수 표시

---

src/navigations/Home.js
src/screens/ChatList.js
src/screens/CreatePost.js
src/screens/Notifications.js

🎨[Style] 게시글 생성 버튼 & 포커스 수정

---

src/screens/ApplicationDecision.js
src/screens/ApplicationList.js
src/screens/SignupDone.js

<br>
신청서 수락/거절 시, 유저 이름 안뜨는 문제 수정
신청서 수락/거절 후, 신청서 목록으로 돌아가질 때 신청자가 그대로 보이는 문제 수정

🐞[bugfix] 신청서 수락//거절 시 발생하는 문제 수정

---

src/components/ChatModal.js
src/contexts/AuthContext.js
src/screens/ApplicationList.js
src/screens/Chat.js
src/screens/EditProfile.js
src/screens/MyPage.js
src/screens/MyPostDetail.js
src/screens/Notifications.js
src/screens/PaymentScreen.js
src/screens/PostDetail.js
src/screens/Profile.js
src/screens/PublicProfile.js
src/utils/utils.js

✨[feature] 세션 이용 결제

---

ios/Podfile.lock
ios/moamoa.xcodeproj/project.pbxproj
src/api/api.js
src/contexts/AuthContext.js
src/screens/Chat.js
src/screens/CheckParticipants.js

✨[feature] 🐞[bugfix] 🎨[style] 환불

---

src/components/LoginModal.js
src/components/index.js
src/hooks/useRequireLogin.js
src/navigations/Home.js
src/navigations/Main.js
src/screens/AllPosts.js
src/screens/Chat.js
src/screens/MyPage.js
src/screens/MyPostDetail.js
src/screens/PostDetail.js
src/screens/Profile.js
src/screens/PublicProfile.js
src/screens/ReviewForm.js
src/theme.js

✨[feature] 리뷰 작성 연결 완료
